name: run AnimehdZerootest

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */7 * * *"   # รันทุก 6 ชม.

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install gdown
        run: pip install gdown

      - name: Python script
        env:
          FILE_URL: ${{ secrets.HDZEROTEST_URL }}   
        run: |
          set +x  
          gdown "$FILE_URL" -O script.py

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run Script
        run: python script.py
